apiVersion: v1
kind: Service
metadata:
  name: nodejs-argo
  labels:
    app: nodejs-argo
spec:
  spec:
  selector:
    app: nodejs-argo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-argo
  labels:
    app: nodejs-argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-argo
  template:
    metadata:
      labels:
        app: nodejs-argo
    spec:
      containers:
      - name: nodejs-argo
        image: yaniemuh19/nodejs-k8s-example:latest
        imagePullPolicy: Always
        env: 
        - name: NODE_PORT
          value: "3000"
        ports:
        - containerPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-cicd
  labels:
    app: nodejs-cicd
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: host1.domain.ext
  - http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: nodejs-cicd
            port:
              number: 80
